<?php

/**
 * @file
 * Contains durhamatletico_core.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\node\Entity\Node;

/**
 * Implements hook_help().
 */
function durhamatletico_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the durhamatletico_core module.
    case 'help.page.durhamatletico_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides core functionality for the Durham Atletico site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function durhamatletico_core_form_node_game_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['title']['#access'] = FALSE;
  $form['title']['widget'][0]['value']['#default_value'] = 'Game';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function durhamatletico_core_form_node_goal_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['title']['#access'] = FALSE;
  $form['title']['widget'][0]['value']['#default_value'] = 'Goal';
}

/**
 * {@inheritdoc}
 */
function durhamatletico_core_node_presave(Drupal\Core\Entity\EntityInterface $entity) {
  if (in_array($entity->getType(), ['game', 'goal'])) {
    \Drupal::service('durhamatletico_core.content_entry')->setTitle($entity);
  }
}

/**
 * {@inheritdoc}.
 */
function durhamatletico_core_node_update(Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getType() === 'game') {
    // Update standings for both teams.
    $home_team = $entity->get('field_home_team')->getValue();
    $away_team = $entity->get('field_away_team')->getValue();
    $teams = array($home_team, $away_team);
    foreach ($teams as $team) {
      $team_node = Node::load($team[0]['target_id']);
      // Get all the games this team has played.
      // Get all the goals this team has scored.
      // Get all the goals in games this team has played that other teams scored.
      // Get all the wins/draws/losses based on analyzing game scores.
      // Update the team node.
    }
  }
}

/**
 * Implements hook_entity_field_access().
 */
function durhamatletico_core_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  if ($account->hasPermission('administer users')) {
    return AccessResult::allowed();
  }
  // If user is looking at their own account, pass.
  if ($operation !== 'view') {
    return AccessResult::neutral();
  }
  list($base, $uid) = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
  if ($base !== 'user') {
    return AccessResult::neutral();
  }
  if ($uid <= 0) {
    return AccessResult::neutral();
  }
  if ($uid == $account->id()) {
    // Let the logged in user look at their account page.
    return AccessResult::neutral();
  }

  // Public fields.
  $public_fields = [
    'field_first_name',
  ];
  if (!in_array($field_definition->getName(), $public_fields)) {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_theme().
 */
function durhamatletico_core_theme() {
  $theme = [];

  return $theme;
}
