---
engines:
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "**/src/test/**"
        - "**/tests/**"
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      encoding: utf-8
      standard: "Drupal"
      ignore_warnings: true
exclude_paths:
- web/core
- web/libraries
- web/modules/contrib
- web/sites

