---
engines:
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
      dead-code-detection: true
  scss-lint:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "**/src/test/**"
        - "**/tests/src/**"
  duplication:
    enabled: true
    config:
      languages:
        - php:
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      encoding: utf-8
      standard: "Drupal"
      ignore_warnings: true
ratings:
  paths:
  - "**.scss"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths:
- "web/core/"
- "web/autoload.php"
- "web/index.php"
- "web/update.php"
- "web/libraries/"
- "web/private/"
- "web/modules/contrib/"
- "web/sites/"
- "**/vendor/**"
- "vendor/"
- "**/tests/**"
- "**/spec/**"
- "config/"
- "console/"
- "drush/"
- "scripts/"
- "sites/"
- ".docker/"

