---
engines:
  scss-lint:
    enabled: true
  sonar-php:
    enabled: true
    config:
      tests_patterns:
        - "**/src/test/**"
        - "**/tests/**"
  phan:
    enabled: true
    config:
      file_extensions: "php,module,inc,install"
  phpmd:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      rulesets: ".phpmd.xml"
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php,inc,module,install"
      encoding: utf-8
      standard: "Drupal"
      ignore_warnings: true
ratings:
  paths:
  - "**.scss"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
exclude_paths:
- "web"
- "!web/modules/custom"
- "!/web/themes/custom"
- "**/vendor/**"
- "vendor/"
- "**/tests/**"
- "**/spec/**"
- "config/"
- "console/"
- "drush/"
- "scripts/"
- "sites/"
- ".docker/"
