scss_files: 'web/themes/custom/atletico/sass/*'

exclude:
  - 'web/themes/custom/atletico/stylesheets/styles.css'
  - 'web/themes/custom/atletico/sass/lib/*'

linters:
  Comment:
    enabled: false
  SelectorDepth:
    enabled: false
  NestingDepth:
    enabled: false
  VendorPrefix:
    enabled: false
  SelectorFormat:
    enabled: false
