definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    enabled: false
    menu_name: main
    parent: ''
    expanded: true
    weight: -50
  comment__admin:
    weight: -68
    menu_name: admin
    parent: system.admin_content
    expanded: false
    enabled: true
