client_key: ''
environment: ''
release: ''
fatal_error_handler: false
fatal_error_handler_memory: 2560
log_levels:
  1: 0
  2: 0
  3: 0
  4: 0
  5: 0
  6: 0
  7: 0
  8: 0
stack: true
timeout: 2
trace: false
javascript_error_handler: false
public_dsn: ''
_core:
  default_config_hash: 2ayuL_RW9YEkCO95d54c8_OyFqzasvXYEZnEZFKZrhk
