max_links: 2000
cron_generate: true
cron_generate_interval: 0
remove_duplicates: true
skip_untranslated: true
batch_process_limit: 1500
base_url: 'https://www.durhamatletico.com'
enabled_entity_types:
  - node
  - taxonomy_term
  - menu_link_content
_core:
  default_config_hash: vLpNUSWP3_hQSpn8ANG15lTltsrKYSu5khPSbspbWuQ
