<?php

/**
 * @file
 * Contains durhamatletico_core.module..
 */

use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\views\Plugin\views\query\Sql;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\Node;
use Drupal\Core\Access\AccessResult;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_help().
 */
function durhamatletico_core_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the durhamatletico_core module.
    case 'help.page.durhamatletico_core':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides core functionality for the Durham Atletico site') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function durhamatletico_core_form_node_game_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['title']['#access'] = FALSE;
  $form['title']['widget'][0]['value']['#default_value'] = 'Game';
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function durhamatletico_core_form_node_goal_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['title']['#access'] = FALSE;
  $form['title']['widget'][0]['value']['#default_value'] = 'Goal';
}

/**
 * {@inheritdoc}
 */
function durhamatletico_core_node_presave(EntityInterface $entity) {
  if (in_array($entity->getType(), ['game', 'goal'])) {
    \Drupal::service('durhamatletico_core.content_entry')->setTitle($entity);
  }
  if ($entity->getType() == 'goal') {
    \Drupal::service('durhamatletico_core.content_entry')->addGoals($entity);
    $entity->set('field_quantity', 1, FALSE);
  }
}

/**
 * {@inheritdoc}.
 */
function durhamatletico_core_node_update(EntityInterface $entity) {
  // Only update standings if the game has been played & is part of a league competition.
  if ($entity->getType() === 'game'
  && $entity->get('field_game_status')->getString() == 'Played') {
    $competition = Node::load($entity->get('field_division')->entity->id());
    if ($competition && in_array($competition->get('field_competition_type')->getString(), ['league', 'tournament'])) {
      \Drupal::service('durhamatletico_core.standings')->updateStandings($entity);
    }
  }
}

/**
 * Implements hook_views_query_alter().
 */
function durhamatletico_core_views_query_alter(ViewExecutable $view, Sql $query) {
  // Use the OR operator to show upcoming home/away games for a team node.
  if ($view->getTitle() == 'Upcoming games' && $view->current_display == 'block_4') {
    $query->where[0]['type'] = 'OR';
  }
  // Use the OR operator to show previous home/away games for a team node.
  if ($view->getTitle() == 'Previous games' && $view->current_display == 'block_8') {
    $query->where[0]['type'] = 'OR';
  }
}

/**
 * Implements hook_entity_field_access().
 */
function durhamatletico_core_entity_field_access($operation, FieldDefinitionInterface $field_definition, AccountInterface $account, FieldItemListInterface $items = NULL) {
  // Restrict access to '/user' URLs for viewing user profiles.
  if (strpos(\Drupal::service('path.current')->getPath(), 'user') !== FALSE) {

    if ($account->hasPermission('administer users')) {
      return AccessResult::allowed();
    }
    // If user is looking at their own account, pass.
    if ($operation !== 'view') {
      return AccessResult::neutral();
    }
    list($base, $uid) = explode('/', trim(\Drupal::service('path.current')->getPath(), '/'));
    if ($base !== 'user') {
      return AccessResult::neutral();
    }
    if ($uid <= 0) {
      return AccessResult::neutral();
    }
    if ($uid == $account->id()) {
      // Let the logged in user look at their account page.
      return AccessResult::neutral();
    }

    // Check for accessing user fields.
    // TODO: This needs to be for any context.
    $public_fields = [
      'field_first_name',
    ];
    if (!in_array($field_definition->getName(), $public_fields)) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_theme().
 */
function durhamatletico_core_theme() {
  $theme = [];

  return $theme;
}
