module:
  automated_cron: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  datetime: 0
  dblog: 0
  durhamatletico_registration: 0
  dynamic_page_cache: 0
  editor: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  kint: 0
  language: 0
  link: 0
  locale: 0
  menu_ui: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rdf: 0
  responsive_image: 0
  search: 0
  shortcut: 0
  stripe_checkout: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  toolbar: 0
  tour: 0
  tracker: 0
  update: 0
  user: 0
  views_ui: 0
  menu_link_content: 1
  content_translation: 10
  views: 10
  standard: 1000
theme:
  classy: 0
  bartik: 0
  seven: 0
  bartletico: 0
  atletico: 0
  stable: 0
