superfish_library: "sites/all/libraries/superfish/jquery.hoverIntent.minified.js\r\nsites/all/libraries/superfish/superfish.js\r\nsites/all/libraries/superfish/supersubs.js\r\nsites/all/libraries/superfish/supposition.js\r\nsites/all/libraries/superfish/sfsmallscreen.js\r\nsites/all/libraries/superfish/sftouchscreen.js"
_core:
  default_config_hash: Bjqe5nqmfnnjecmHHxF6rltZFcKRKgSVsC_shaV8prs
