favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: false
  logo: true
logo:
  path: 'public://DA_Logo_Version-03-small.png'
  url: ''
  use_default: false
