<?php

/**
 * @file
 * Contains durhamatletico_registration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function durhamatletico_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the durhamatletico_registration module.
    case 'help.page.durhamatletico_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides registration functionality for Durham Atletico leagues.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function durhamatletico_registration_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if ($form_id == 'node_registration_form') {
    if (\Drupal::currentUser()->hasPermission('administer content')) {
      return;
    }
    unset($form['revision_information']);
    unset($form['revision_log']);
    $form['title']['#access'] = FALSE;
    $form['title']['widget'][0]['value']['#default_value'] = \Drupal::currentUser()->getDisplayName();
  }
}

/**
 * Implements hook_node_access().
 */
function durhamatletico_registration_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  $type = $node->bundle();
  if ($type == 'registration' && $op == 'view') {
    if ($account->hasPermission('administer content')) {
      return \Drupal\Core\Access\AccessResult::allowed();
    }
    if ($node->getOwner()->getAccountName() === $account->getAccountName()) {
      return \Drupal\Core\Access\AccessResult::allowed();
    }
    return \Drupal\Core\Access\AccessResult::forbidden();
  }

//  switch ($op) {
//    case 'create':
//      return AccessResult::allowedIfHasPermission($account, 'create ' . $type . ' content');
//
//    case 'update':
//      if ($account->hasPermission('edit any ' . $type . ' content', $account)) {
//        return AccessResult::allowed()->cachePerPermissions();
//      }
//      else {
//        return AccessResult::allowedIf($account->hasPermission('edit own ' . $type . ' content', $account) && ($account->id() == $node->getOwnerId()))->cachePerPermissions()->cachePerUser()->cacheUntilEntityChanges($node);
//      }
//
//    case 'delete':
//      if ($account->hasPermission('delete any ' . $type . ' content', $account)) {
//        return AccessResult::allowed()->cachePerPermissions();
//      }
//      else {
//        return AccessResult::allowedIf($account->hasPermission('delete own ' . $type . ' content', $account) && ($account->id() == $node->getOwnerId()))->cachePerPermissions()->cachePerUser()->cacheUntilEntityChanges($node);
//      }
//
//    default:
//      // No opinion.
//      return AccessResult::neutral();
//  }
  return \Drupal\Core\Access\AccessResult::neutral();
}

/**
 * Implements hook_theme().
 */
function durhamatletico_registration_theme() {
  $theme = [];

  return $theme;
}
